services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_URL: http://localhost:5050
    ports:
      - "3000:80"
    depends_on:
      - backend
