services:
  - type: web
    name: bioquery-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
  
  - type: web
    name: bioquery-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    plan: free
    dockerContext: .
    buildCommand: docker build --build-arg REACT_APP_API_URL=https://bioquery-backend.onrender.com -f ./Dockerfile.frontend .